version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
